language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "Pre-testing installs"

# Scripts to be run
before_script:
  - docker --version # Print the version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed binhpm/udagram-api-feed:latest
  - docker tag udagram-api-user binhpm/udagram-api-user:latest
  - docker tag udagram-frontend binhpm/udagram-frontend:latest
  - docker tag reverseproxy binhpm/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push binhpm/udagram-api-feed:latest
  - docker push binhpm/udagram-api-user:latest
  - docker push binhpm/udagram-frontend:latest
  - docker push binhpm/reverseproxy:latest